---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  prefix: /
  host: "dashboard.hephy.pro"
  # host_regex: true
  host_rewrite: web.linkerd-viz.svc.cluster.local:8084
  service: web.linkerd-viz.svc.cluster.local:8084
  rewrite: ""
  allow_upgrade:
  - websocket
  remove_request_headers:
  - Origin
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: dashboard
  namespace: default
spec:
  hostname: "dashboard.hephy.pro"
  acmeProvider:
    email: ambassador-cert-hephy@nerdland.info
