---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: emojivoto
  namespace: emojivoto
spec:
  hostname: "emojivoto.hephy.pro"
  acmeProvider:
    email: ambassador-cert-hephy@nerdland.info
