namespace: podinfo
bases:
  - github.com/kingdonb/podinfo/kustomize/?ref=6.0.1

resources:
  - frontend.yaml
# - ns.yaml
  - canary.yaml
  - generator.yaml
  - mapping.yaml
  - host.yaml

patchesStrategicMerge:
  - patch.yaml
