apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    metadata:
      annotations:
    spec:
      containers:
        - name: podinfod
          image: docker.io/kingdonb/podinfo:6.0.1 # {"$imagepolicy": "flux-system:podinfo"}
          securityContext:
            runAsUser: 1337
          env:
            - name: PODINFO_UI_COLOR
              value: '#C99700' # #00843D #0C2340 #AE9142
            # - name: PODINFO_UI_LOGO
            #   value: https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_bunny.gif
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
$patch: delete
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
