---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: blog-teamhephy-info
  namespace: default
spec:
  hostname: "blog.teamhephy.info"
  acmeProvider:
    email: ambassador-cert-hephy@nerdland.info
